version: '3.4'

services:
  server:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./wheelhouse:/server/wheelhouse
    ports:
      - "8001:8001"
  test:
    build:
      context: ./
      dockerfile: docker/Dockerfile_test
    ports:
      - "8002:8002"
