version: '3.4'

services:
  ubuntu:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./wheelhouse:/server/wheelhouse
      - ./pyproject.toml:/server/pyproject.toml
      - ./setup.py:/server/setup.py
    ports:
      - "8001:8001"
  pytest:
    build:
      context: ./
      dockerfile: docker-pytest/Dockerfile
    ports:
      - "8002:8002"
  manylinux:
    build:
      context: ./
      dockerfile: docker-manylinux/Dockerfile
    volumes:
      - ./wheelhouse:/server/wheelhouse
    ports:
      - "8003:8003"