[project]
name = "pycades"
readme = "README.md"
version = "1.1.3"

[project.urls]
homepage = "https://docs.cryptopro.ru/cades/pycades"
documentation = "https://docs.cryptopro.ru/cades/pycades"
source = "https://github.com/KirillOgleznev/pycades"